### ISSUE TITLE
AssertionError: B has incorrect shape

### ISSUE THREAD

**Issue by grferna** [cweniger/swordfish#3]
Hello,

I've just installed the swordfish-1.0.2 on python 3.8.5.

Running the example notebook swordfish_ID.ipynb I get the following error on "AssertionError: B has incorrect shape" on cell 7.

I've also run the notebook swordfish_DD.ipynb and here I do not found errors.

Gonzalo.

**Comment by tedwards2412** [comment]
Thanks for spotting this issue. The original version of swordfish was only tested on python2. I've pushed a fix to the notebook, so it should work now

**Comment by grferna** [comment]
It is working!

Thanks!
